Mckin 24785 v3
open-craft/problem-builder pull request #305
Opened 2020-09-24 06:38 UTC by wasifarbisoft

2020-09-24 21:53 UTC, wasifarbisoft commented
@xitij2000 Please review this Pull Request

2020-09-25 09:26 UTC, aayushagra requested changes
@wasifarbisoft Why are there pointless merge commits merging PR #1  and #4 ? Can you clean up the commit history please

2020-09-25 09:26 UTC, aayushagra commented on problem_builder/mixins.py
> +PB_LANGUAGE_JS_DIRECTORY_MAP = {
@xitij2000 @wasifarbisoft Shouldn't this data be loaded from a configuration file instead of being hardcoded?

2020-09-25 11:28 UTC, wasifarbisoft commented
@aayushagra ,
I was unable to remove the pointless commit form this PR maybe they were added due to the stale branch I had for Problem

I am closing this Pull Request and created a new branch with clean commits
New Branch is https://github.com/open-craft/problem-builder/pull/307

2020-09-25 11:28 UTC, closed without merging